on: [pull_request]
name: Build PR preview

jobs:
  build:
    uses: ./.github/workflows/build-website.yml
  publish-pr-number:
    runs-on: ubuntu-latest
    steps:
      - name: Write PR Number to file
        env: 
          PR_NUMBER: ${{ github.event.number }}
        run: echo $PR_NUMBER > ./pr/pr_number
      - name: Upload PR Number as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr_number
          path: pr/