on:
  workflow_run:
    workflows: ["Build PR preview"]
    types: [completed]
name: Publish PR preview

jobs:
  get-pr-number:
    # We need the PR number to generate the branch URL for Cloudflare Pages, but GitHub doesn't seem to have a way to derive the PR number (or receive any input at all) from the triggering workflow, so we use artifacts instead.
    name: Get PR Number
    runs-on: ubuntu-latest
    outputs:
      pr-number: ${{ steps.output-pr-number.pr-number }}
      hardcoded: A hardcoded value
    permissions:
      actions: read
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download Artifact from triggering workflow
        env:
          RUN_ID: ${{ github.event.workflow_run.id }}
          GITHUB_TOKEN: ${{ secrets.COZY_PAT }}
        uses: actions/download-artifact@v4
        with:
          name: pr_number
          path: pr
          run-id: ${{ env.RUN_ID }}
          github-token: ${{ env.GITHUB_TOKEN }}
      - name: Output PR Number
        id: output-pr-number
        run: echo "pr-number=$(cat ./pr/pr_number)" >> "$GITHUB_OUTPUT"
    
  # publish-preview:
  #   uses: ./.github/workflows/publish.yml
  #   needs: get-pr-number
  #   with:
  #     branch: preview-${{ needs.get-pr-number.outputs.pr-number }}
  #     run-id: ${{ github.event.workflow_run.id }}
  #   secrets: inherit
  echo-tests:
    runs-on: ubuntu-latest
    needs: get-pr-number
    env:
      EXPECTED_OUTPUT: preview-${{ needs.get-pr-number.outputs.pr-number }}
      HARDCODED_OUTPUT: ${{ needs.get-pr-number.outputs.hardcoded }}
    steps:
      - name: Echo expected outputs
        run: echo "$(EXPECTED_OUTPUT)\n$(HARDCODED_OUTPUT)"
